# Generated by Django 4.0.3 on 2022-04-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugahfree', '0002_input_created_input_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
