# Generated by Django 4.0.4 on 2022-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_input_carbs_in_grams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='carbs_in_grams',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='input',
            name='insulin_in_units',
            field=models.IntegerField(),
        ),
    ]
